### ISSUE TITLE
company-box clips off to the edge of the screen

### ISSUE THREAD

**Issue by SreenivasVRao** [sebastiencs/company-box#165] opened 2021-05-01 23:43 UTC
https://i.imgur.com/cF1DBCD.png

As you can see - the doc string shows up in a childframe which doesn't wrap at the edge of the screen. On dual monitors, the problem is that the doc string shows up in a childframe spanning multiple monitors:

https://media.discordapp.net/attachments/406554085794381833/825157364344029274/Screen_Shot_2021-03-26_at_7.55.13_PM.png?width=2160&height=375

Any advice on how to overcome this? I'm using doom emacs.

**Comment by HawkinsT** [comment] 2021-09-20 18:51
I have the same issue. I'm very new to emacs and don't know elisp so a 'proper' solution that could form a pull request is beyond me, however you can manualy set the documentation frame size [here](https://github.com/sebastiencs/company-box/blob/156f65cfbf690ed84e0e84f90277d665d873ff24/company-box-doc.el#L80). I've changed mine to `((width . height) (window-text-pixel-size window nil nil 800 10000))`, for instance. The quickest way to implement this is to modify this file under `~/.emacs.d/elpa/` and then `M-x emacs-lisp-byte-compile-and-load`.

**Comment by NightMachinary** [comment] 2021-09-21 16:11
Patching the mentioned line, the problem is that the frame is not soft-wrapping at all:
![image](https://user-images.githubusercontent.com/36224762/134207360-f18f2356-2842-46e2-a0f1-787eeebe181a.png)

**Comment by NightMachinary** [comment] 2021-09-21 16:21
To fix this, I needed to add `(toggle-truncate-lines -1)` to the end of the function `company-box-doc--make-buffer`.

```elisp
(defun company-box-doc--make-buffer (object)
  (let* ((buffer-list-update-hook nil)
         (inhibit-modification-hooks t)
         (string (cond ((stringp object) object)
                       ((bufferp object) (with-current-buffer object (buffer-string))))))
    (when (and string (> (length (string-trim string)) 0))
      (with-current-buffer (company-box--get-buffer "doc")
        (erase-buffer)
        (insert string)
        (setq mode-line-format nil
              display-line-numbers nil
              header-line-format nil
              show-trailing-whitespace nil
              cursor-in-non-selected-windows nil)

        (toggle-truncate-lines -1) ;; PATCHED HERE

        (current-buffer)))))
```

BTW, you do not need to edit the original files. You can copy the functions to your own personal config and edit them there; The new definitions would override the old ones (if you load `company-box` before them).

I hope these two patches are merged into the master, as the current behavior is only suitable if you have a huge monitor.

![image](https://user-images.githubusercontent.com/36224762/134208542-bd6adb16-1878-47a8-9040-2102199d61c3.png)

**Comment by HawkinsT** [comment] 2021-09-21 18:57
Thanks, I've just proposed a commit that makes the above the default behaviour. I've also added the company-box-doc-no-wrap option in case anyone wishes to keep the existing behaviour.

**Comment by SreenivasVRao** [comment] 2021-12-01 17:04
@sebastiencs any chance you can review this soon? :)

**Closed** 2022-09-09 20:20 UTC
