### ISSUE TITLE
Error Symbol’s function definition is void: company-box-icons-image

### ISSUE THREAD

**Issue by dinkonin** [sebastiencs/company-box#104] opened 2020-08-03 08:26 UTC
Hello after the latest update company-box stopped working for me with this error 

> Error (use-package): company/:config: Symbol’s function definition is void: company-box-icons-image

I load it like this `(use-package company-box :hook (company-mode . company-box-mode))`

I'm on emacs 27 (arch linux AUR).

**Comment by marodoncat** [comment] 2020-08-03 11:45
I got the same error, but after removing the package and re-installing it went away.

**Comment by dinkonin** [comment] 2020-08-03 11:55
> I got the same error, but after removing the package and re-installing it went away.

Just tried it, but unfortunately I'm getting the same error after reinstalling and restarting emacs.

**Comment by sebastiencs** [comment] 2020-08-03 12:06
@dinkonin Can you try to run (`M-:`):
```
(byte-recompile-directory (file-name-directory (find-library-name "company-box")) 0 t)
```

**Comment by dinkonin** [comment] 2020-08-03 12:12
@sebastiencs I get this:
```
Compiling file /home/dinkonin/.config/emacs/packages/company-box/company-box-doc.el at Mon Aug  3 15:09:11 2020
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type
company-box-doc.el:44:1:Warning: defcustom for ‘company-box-doc-delay’ fails
    to specify type

Compiling file/home/dinkonin/.config/emacs/packages/company-box/company-box-icons.el at Mon Aug  3 15:09:11 2020

In end of data:
company-box-icons.el:336:1:Warning: the following functions are not known to be defined:
    all-the-icons-faicon, all-the-icons-octicon,
    all-the-icons-alltheicon, all-the-icons-material

Compiling file /home/dinkonin/.config/emacs/packages/company-box/company-box.el at Mon Aug  3 15:09:11 2020

Compiling internal form(s) at Mon Aug  3 15:09:13 2020
```

If I remove `company-box-icons.elc` the problem dissapears.

**Comment by sebastiencs** [comment] 2020-08-03 12:14
@dinkonin The issue is now fixed with https://github.com/sebastiencs/company-box/commit/b7ca474ccf5bdee663cd807ae4a9b01569e4bc39

**Comment by dinkonin** [comment] 2020-08-03 12:18
I can confirm that the issue is fixed. Thank you !

**Closed** 2020-08-03 12:18 UTC
